spring.application.name=chiadata
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/dudi_chiadata}
server.port=${PORT:8080}

# JWT Configuration
dudi.app.jwtSecret=${DUDI_APP_JWT_SECRET:=======================DudiChiaDataSecretKeyJWTTokenSigningKey2026======================}
dudi.app.jwtExpirationMs=86400000

# Server logging settings
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

